### PR TITLE
Ibra

### PR DESCRIPTION
**Pull request by ibrahimilhan35**

### CODE REVIEW

**Review by RaiSaw — COMMENTED** [review]
this looks cool,(haven't done this here yet)- i just know creating thread/s on gitlab, code is cleaner

**Comment by tzuhuangyen** [comment]
is this for Week 15 Class 1 Homework - Code Review?

**Comment by ibrahimilhan35** [comment]
> this looks cool,(haven't done this here yet)- i just know creating thread/s on gitlab, code is cleaner

Thank you RaiSaw ;)) I think this repo is an older version of my website..

**Comment by ibrahimilhan35** [comment]
> is this for Week 15 Class 1 Homework - Code Review?

 I don't know, is it? If so, are we done with the homework? ;))

**Comment by tzuhuangyen** [comment]
> > is this for Week 15 Class 1 Homework - Code Review?
> 
> I don't know, is it? If so, are we done with the homework? ;))

im not sure how is working, but i guess at least we have to make a merge request on GitHub

**Pull request merged**
